# Generated by Django 6.0.4 on 2026-05-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("entidad", models.CharField(max_length=100)),
                ("entidad_id", models.IntegerField()),
                ("datos_anteriores", models.JSONField(blank=True, null=True)),
                ("datos_nuevos", models.JSONField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, default="", max_length=50)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acciones_auditadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(fields=["entidad"], name="idx_audit_entidad"),
                    models.Index(fields=["accion"], name="idx_audit_accion"),
                    models.Index(fields=["fecha_hora"], name="idx_audit_fecha"),
                    models.Index(fields=["usuario"], name="idx_audit_usuario"),
                ],
            },
        ),
    ]
