# Generated by Django 6.0.4 on 2026-05-17 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0002_observaciondiaria_turnomedico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("taller", "Taller"),
                            ("fisioterapia", "Fisioterapia"),
                            ("cumpleanos", "Cumpleaños"),
                            ("recreativa", "Recreativa"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("responsable", models.CharField(max_length=150)),
                ("fecha_hora", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=20,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actividades",
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="ActividadResidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="actividades.actividad",
                    ),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_actividad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_asignadas",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "db_table": "actividad_residentes",
            },
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(fields=["estado"], name="idx_actividades_estado"),
        ),
        migrations.AddIndex(
            model_name="actividad",
            index=models.Index(fields=["fecha_hora"], name="idx_actividades_fecha"),
        ),
        migrations.AlterUniqueTogether(
            name="actividadresidente",
            unique_together={("actividad", "residente")},
        ),
    ]
