# Generated by Django 6.0.4 on 2026-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="observaciones",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="actividad",
            name="tipo_otro",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("taller", "Taller"),
                    ("fisioterapia", "Fisioterapia"),
                    ("cumpleanos", "Cumpleaños"),
                    ("recreativa", "Recreativa"),
                    ("deportivo", "Deportivo"),
                    ("otro", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
