sonar.projectKey=ryzzvass-art_asilo_virtual 
sonar.organization=ryzzvass-art

# Origen del código
sonar.sources=.
sonar.python.version=3

# Excluir archivos que no son lógica de negocio
sonar.exclusions=**/migrations/**, **/tests/**, manage.py, **/settings.py