# Generated by Django 6.0.4 on 2026-05-02 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0001_initial"),
        ("residentes", "0002_observaciondiaria_turnomedico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidenteMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosis", models.CharField(max_length=100)),
                ("via_administracion", models.CharField(max_length=50)),
                ("horarios", models.JSONField(default=list)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("finalizado", "Finalizado")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones",
                        to="medicamentos.catalogomedicamento",
                    ),
                ),
                (
                    "prescrito_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos_prescritos",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "db_table": "residente_medicamentos",
            },
        ),
        migrations.CreateModel(
            name="AdministracionMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("administrado", models.BooleanField()),
                ("fecha_hora_programada", models.DateTimeField()),
                ("fecha_hora_real", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, default="")),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administraciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente_medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administraciones",
                        to="medicamentos.residentemedicamento",
                    ),
                ),
            ],
            options={
                "db_table": "administraciones_medicamento",
                "ordering": ["-fecha_hora_programada"],
            },
        ),
    ]
