# Generated by Django 6.0.4 on 2026-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0003_movimientostock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmedicamento",
            name="observaciones",
            field=models.TextField(blank=True, default=""),
        ),
    ]
