# Generated by Django 6.0.4 on 2026-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0004_stockmedicamento_observaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogomedicamento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
