# Generated by Django 6.0.4 on 2026-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0005_catalogomedicamento_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogomedicamento",
            name="observaciones",
            field=models.TextField(blank=True, default=""),
        ),
    ]
