# Generated by Django 6.0.4 on 2026-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0006_catalogomedicamento_observaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="administracionmedicamento",
            name="corregida",
            field=models.BooleanField(default=False),
        ),
    ]
