# Generated by Django 6.0.4 on 2026-05-17 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residentes", "0002_observaciondiaria_turnomedico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("dni", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visitantes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visitantes",
            },
        ),
        migrations.CreateModel(
            name="VisitanteResidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relacion",
                    models.CharField(
                        choices=[
                            ("familiar", "Familiar"),
                            ("amigo", "Amigo"),
                            ("representante_legal", "Representante legal"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("suspendido", "Suspendido")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_autorizacion", models.DateTimeField(auto_now_add=True)),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autorizaciones_visita",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitantes_autorizados",
                        to="residentes.residente",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorizaciones",
                        to="visitas.visitante",
                    ),
                ),
            ],
            options={
                "db_table": "visitante_residente",
                "unique_together": {("visitante", "residente")},
            },
        ),
        migrations.CreateModel(
            name="RegistroVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_entrada", models.DateTimeField(auto_now_add=True)),
                ("fecha_hora_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("finalizada", "Finalizada"),
                            ("pendiente_cierre", "Pendiente de cierre"),
                        ],
                        default="en_curso",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visitas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitante_residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="visitas.visitanteresidente",
                    ),
                ),
            ],
            options={
                "db_table": "registros_visita",
                "ordering": ["-fecha_hora_entrada"],
            },
        ),
    ]
