# Generated by Django 6.0.4 on 2026-06-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="dni",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
