# Generated by Django 6.0.4 on 2026-05-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_observaciondiaria_turnomedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grupo_alimentario', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('activo', 'Activo'), ('archivado', 'Archivado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalogo_alimentos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoRestriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('condiciones_asociadas', models.CharField(blank=True, default='', max_length=255)),
                ('severidad', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('recomendado', 'Recomendado')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restricciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalogo_restricciones',
            },
        ),
        migrations.CreateModel(
            name='AlimentoRestriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_que_viola', to='nutricion.catalogoalimento')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_afectados', to='nutricion.catalogorestriccion')),
            ],
            options={
                'db_table': 'alimento_restricciones',
            },
        ),
        migrations.CreateModel(
            name='ResidenteRestriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('revocada', 'Revocada')], default='activa', max_length=20)),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restricciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_alimentarias', to='residentes.residente')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes_con_restriccion', to='nutricion.catalogorestriccion')),
            ],
            options={
                'db_table': 'residente_restricciones',
            },
        ),
        migrations.AddIndex(
            model_name='catalogoalimento',
            index=models.Index(fields=['estado'], name='idx_alimentos_estado'),
        ),
        migrations.AddIndex(
            model_name='catalogorestriccion',
            index=models.Index(fields=['estado'], name='idx_restricciones_estado'),
        ),
        migrations.AddIndex(
            model_name='catalogorestriccion',
            index=models.Index(fields=['severidad'], name='idx_restricciones_severidad'),
        ),
        migrations.AlterUniqueTogether(
            name='alimentorestriccion',
            unique_together={('alimento', 'restriccion')},
        ),
        migrations.AlterUniqueTogether(
            name='residenterestriccion',
            unique_together={('residente', 'restriccion')},
        ),
    ]
