# Generated by Django 6.0.4 on 2026-05-05 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutricion", "0001_initial"),
        ("residentes", "0002_observaciondiaria_turnomedico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanNutricional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dieta",
                    models.CharField(
                        choices=[
                            ("blanda", "Blanda"),
                            ("hipocalorica", "Hipocalórica"),
                            ("normal", "Normal"),
                            ("diabetica", "Diabética"),
                            ("hiposodica", "Hiposódica"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("vigente", "Vigente"), ("archivado", "Archivado")],
                        default="vigente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_nutricionales",
                        to="residentes.residente",
                    ),
                ),
            ],
            options={
                "db_table": "planes_nutricionales",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ComidaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_comida",
                    models.CharField(
                        choices=[
                            ("desayuno", "Desayuno"),
                            ("almuerzo", "Almuerzo"),
                            ("merienda", "Merienda"),
                            ("cena", "Cena"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion_menu", models.TextField(blank=True, default="")),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="en_comidas",
                        to="nutricion.catalogoalimento",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comidas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comidas",
                        to="nutricion.plannutricional",
                    ),
                ),
            ],
            options={
                "db_table": "comidas_diarias",
                "ordering": ["fecha", "tipo_comida"],
            },
        ),
    ]
