# Generated by Django 6.0.4 on 2026-06-02 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutricion", "0002_plannutricional_comidadiaria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannutricional",
            name="estado",
            field=models.CharField(
                choices=[
                    ("vigente", "Vigente"),
                    ("archivado", "Archivado"),
                    ("asignado", "En proceso de asignación"),
                ],
                default="vigente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlantillaNutricional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo_dieta",
                    models.CharField(
                        choices=[
                            ("blanda", "Blanda"),
                            ("hipocalorica", "Hipocalórica"),
                            ("normal", "Normal"),
                            ("diabetica", "Diabética"),
                            ("hiposodica", "Hiposódica"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de aprobación"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantillas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plantillas_nutricionales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComidaPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comida",
                    models.CharField(
                        choices=[
                            ("desayuno", "Desayuno"),
                            ("almuerzo", "Almuerzo"),
                            ("merienda", "Merienda"),
                            ("cena", "Cena"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion_menu", models.TextField(blank=True, default="")),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="en_plantillas",
                        to="nutricion.catalogoalimento",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comidas",
                        to="nutricion.plantillanutricional",
                    ),
                ),
            ],
            options={
                "db_table": "comidas_plantilla",
                "ordering": ["tipo_comida"],
            },
        ),
        migrations.AddField(
            model_name="plannutricional",
            name="plantilla_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planes_asignados",
                to="nutricion.plantillanutricional",
            ),
        ),
        migrations.AddIndex(
            model_name="plantillanutricional",
            index=models.Index(fields=["estado"], name="idx_plantillas_estado"),
        ),
    ]
