# Generated by Django 6.0.4 on 2026-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nutricion",
            "0003_alter_plannutricional_estado_plantillanutricional_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantillanutricional",
            name="fecha_menu",
            field=models.DateField(default="2026-06-01"),
            preserve_default=False,
        ),
    ]
