# Generated by Django 6.0.4 on 2026-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutricion", "0004_plantillanutricional_fecha_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogoalimento",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="plannutricional",
            name="estado",
            field=models.CharField(
                choices=[("vigente", "Vigente"), ("archivado", "Archivado")],
                default="vigente",
                max_length=20,
            ),
        ),
    ]
