# Generated by Django 6.0.4 on 2026-04-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_login",
        ),
    ]
