# Generated by Django 6.0.4 on 2026-04-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('hospitalizado', 'Hospitalizado'), ('dado_de_alta', 'Dado de alta')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'residentes',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticos', models.TextField(blank=True, default='')),
                ('alergias', models.TextField(blank=True, default='')),
                ('condiciones_cronicas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='residentes.residente')),
            ],
            options={
                'db_table': 'historial_medico',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('familiar', 'Familiar directo'), ('medico_cabecera', 'Médico de cabecera')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('relacion_cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='residentes.residente')),
            ],
            options={
                'db_table': 'contactos_emergencia',
            },
        ),
        migrations.AddIndex(
            model_name='residente',
            index=models.Index(fields=['estado'], name='idx_residentes_estado'),
        ),
        migrations.AddIndex(
            model_name='residente',
            index=models.Index(fields=['dni'], name='idx_residentes_dni'),
        ),
        migrations.AlterUniqueTogether(
            name='contactoemergencia',
            unique_together={('residente', 'tipo')},
        ),
    ]
