# Generated by Django 6.0.4 on 2026-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residentes", "0002_observaciondiaria_turnomedico"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactoemergencia",
            name="dni",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="historialmedico",
            name="tratamiento",
            field=models.TextField(blank=True, default=""),
        ),
    ]
