# Generated by Django 6.0.4 on 2026-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residentes", "0003_contactoemergencia_dni_historialmedico_tratamiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residente",
            name="dni",
            field=models.CharField(
                error_messages={"unique": "Ya existe un residente con este C.I."},
                max_length=20,
                unique=True,
            ),
        ),
    ]
